[package]
name = "dedup"
version = "0.1.0"
edition = "2024"

[dependencies]

[[bin]]
name = "add-two-numbers"
path = "add-two-numbers/src/main.rs"

[[bin]]
name = "longest-substring-without-repeating-characters"
path = "longest-substring-no-rep/src/main.rs"