[package]
name = "rocket-practice"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.1"
#Logging using tracing
#tracing = "0.1.41"
#tracing-subscriber = "0.3.18"
log = "0.4"
env_logger = "0.11.5"