use rayon::prelude::*;
fn main() {

    let tuple_list = vec![
        ("Yoda", 42),
        ("Luke", 24),
        ("Leia", 24),
        ("Anakin", 42),
        ("Padme", 42),
        ("Obi", 38),
        ("Han", 33),
        ("Chewbacca", 33),
        ("Vader", 52),
        ("Palpatine", 52),
        ("Boba", 32),
        ("Lando", 44),
        ("Rey", 19),
        ("Finn", 23),
        ("Poe", 32),
        ("Phasma", 32),
        ("Hux", 32),
        ("Kylo", 29),
        ("Jabba", 33),
        ("Wicket", 9),
        ("Ackbar", 51),
        ("Tarkin", 64),
        ("Maul", 54),
        ("Qui-Gon", 60),
        ("Dooku", 83),
        ("Grievous", 55),
        ("Jango", 66),
        ("Plo", 52),
        ("Ahsoka", 14),
        ("Ventress", 40),
        ("Sebulba", 16),
        ("Jabba", 33),
        ("Wicket", 9),
        ("Ackbar", 51),
        ("Tarkin", 64),
        ("Maul", 54),
        ("Qui-Gon", 60),
        ("Dooku", 83),
        ("Grievous", 55),
        ("Jango", 66),
        ("Plo", 52),
        ("Ahsoka", 14),
        ("Ventress", 40),
        ("Sebulba", 16),
        ("Jabba", 33),
        ("Wicket", 9),
        ("Ackbar", 51),
        ("Tarkin", 64),
        ("Maul", 54),
        ("Qui-Gon", 60),
        ("Dooku", 83),
        ("Grievous", 55),
        ("Jango", 66),
        ("Plo", 52),
        ("Ahsoka", 14),
        ("Ventress", 40),
        ("Sebulba", 16),
        ("Jabba", 33),
        ("Wicket", 9),
        ("Ackbar", 51),
        ("Tarkin", 64),
        ("Maul", 54),
        ("Qui-Gon", 60),
        ("Dooku", 83),
        ("Grievous", 55),
        ("Jango", 66),
        ("Plo", 52),
        ("Ahsoka", 14),
        ("Ventress", 40),
        ("Sebulba", 16),
        ("Jabba", 33),
        ("Wicket", 9),
        ("Ackbar", 51),
        ("Tarkin", 64),
        ("Maul", 54),
    ];

    let mut sorted_unique_list = tuple_list
        .into_par_iter()
        .map(|(name, age)| (name.to_string(), age))
        .collect::<Vec<(String, i32)>>();
    sorted_unique_list.par_sort_unstable_by_key(|x| x.1);
    sorted_unique_list.dedup();

    println!("{:?}", sorted_unique_list[0..5].to_vec());
}
