[package]
name = "twitter_mock_analysis"
version = "0.1.0"
edition = "2021"

[dependencies]
neo4rs = "0.8.0"
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
log = "0.4.22"
