[package]
name = "i2c_practice"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
 plotters = { version = "^0.3.5", default_features = true, features = ["evcxr", "all_series", "all_elements"] }