[package]
name = "distrosless-tokenizer"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
serde = { version = "1.0.215", features = ["derive"] }
tokenizers = { version = "0.20.3", features = ["http"] }
